hours/hours/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.conf import settings

urlpatterns = [
    path("wisehours/admin/", admin.site.urls),
    path("wisehours/api-auth/", include("rest_framework.urls")),
    path("wisehours/", include("sheets.urls")),
    # redirect root to the app prefix explicitly (use absolute path to avoid
    # unexpected relative-resolution to the package name)
    path("", RedirectView.as_view(url="/wisehours/", permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hours/sheets/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from . import views, api_views, login_views

app_name = "sheets"

urlpatterns = [
    path("", RedirectView.as_view(url="home", permanent=True)),
    path("home", views.HomePageView.as_view(), name="home_page"),
    path("signup", login_views.signup, name="signup"),
    path("login", login_views.login, name="login"),
    path("change_password", login_views.change_password, name="change_password"),
    path("logout", login_views.logout, name="logout"),
    path("hours", views.HoursView.as_view(), name="hours"),
    path("hours_info", views.HoursInfoView.as_view(), name="hours_info"),
    path("personal_info", views.PersonalInfoView.as_view(), name="personal_info"),
    path("daily_report", views.DailyReport.as_view(), name="daily_report"),
    path("daily_report_management", views.DailyReportManagement.as_view(), name="daily_report_management"),
    path("payment", views.PaymentHandleView.as_view(), name="payment"),
    path("order_food_form", views.FoodFormView.as_view(), name="food_form"),
    path("alter_food_data", views.FoodDataView.as_view(), name="food_data"),
    path("reports", views.ReportsView.as_view(), name="reports"),
    path("detailed_report", views.DetailedReportView.as_view(), name="detailed_report"),
    path("main_report", views.MainReportView.as_view(), name="main_report"),
    path(
        "users_monthly_report",
        views.UsersMonthlyReportView.as_view(),
        name="users_monthly_report",
    ),
    path(
        "projects_yearly_report",
        views.ProjectsYearlyReportView.as_view(),
        name="projects_yearly_report",
    ),
    path("payment_export", views.PaymentExportView.as_view(), name="payment_export"),
    path(
        "payment_excel_export/<str:year>/<str:month>",
        views.PaymentExcelExportView.as_view(),
        name="payment_excel_export",
    ),
    path(
        "payment_excel_import/<str:year>/<str:month>",
        views.PaymentExcelImportView.as_view(),
        name="payment_excel_import",
    ),
    path("api/info", api_views.InfoApiView.as_view(), name="api_info"),
    path("api/projects", api_views.ProjectListApiView.as_view(), name="api_projects"),
    path(
        "api/sheets/<str:year>/<str:month>",
        api_views.SheetApiView.as_view(),
        name="api_sheets",
    ),
    path(
        "api/public_monthly_report/<str:year>/<str:month>",
        api_views.PublicMonthlyReportApiView.as_view(),
        name="api_public_monthly_report",
    ),
    path(
        "api/monthly_report/<str:year>/<str:month>",
        api_views.MonthlyReportApiView.as_view(),
        name="api_monthly_report",
    ),
    path(
        "api/payment/<str:year>/<str:month>",
        api_views.PaymentApiView.as_view(),
        name="api_payment",
    ),
    path(
        "api/public_payment/<str:year>/<str:month>",
        api_views.PublicPaymentApiView.as_view(),
        name="api_public_payment",
    ),
    path(
        "api/FoodManagement/<str:year>/<str:month>",
        api_views.FoodManagementApiView.as_view(),
        name="api_FoodManagement",
    ),
    path(
        "api/food_cost_management/<str:year>/<str:month>",
        api_views.FoodCostManagementApiView.as_view(),
        name="api_FoodCostManagement",
    ),
    path(
        "api/FoodData/<str:year>/<str:month>",
        api_views.FoodDataApiView.as_view(),
        name="api_FoodData",
    ),
    path(
        "api/order_food/<str:year>/<str:month>",
        api_views.OrderFoodApiView.as_view(),
        name="api_order_food",
    ),
    path(
        "api/daily_foods_order/<str:year>/<str:month>/<str:weekIndex>/<str:day>",
        api_views.DailyFoodsOrder.as_view(),
        name="api_daily_foods_order",
    ),
    path(
        "api/daily_report_user/<str:year>/<str:month>/<str:day>",
        api_views.DailyReportUser.as_view(),
        name="api_daily_report_user",
    ),
    path(
        "api/daily_report_management/<str:year>/<str:month>",
        api_views.DailyReportManagement.as_view(),
        name="api_daily_report_management",
    ),
    path(
        "api/daily_report_setting_management",
        api_views.DailyReportSettingManager.as_view(),
        name="daily_report_setting_management",
    ),
]

hours/sheets/views.py
from django.views.generic.base import TemplateView, View
from django.http import HttpResponse, JsonResponse
from django.utils.decorators import method_decorator
from sheets.customDecorators import *
from django.db.models import QuerySet

import pandas as pd
import numpy as np
import io
import json
import jdatetime as jdt
import openpyxl
from io import BytesIO

from sheets.models import Sheet, User
from sheets.api_views import MonthlyReportApiView


class JSONResponseMixin:
    """
    A mixin that can be used to render a JSON response.
    """

    def render_to_json_response(self, context, **response_kwargs):
        """
        Returns a JSON response, transforming 'context' to make the payload.
        """
        return JsonResponse(self.get_data(context), **response_kwargs)

    def get_data(self, context):
        """
        Returns an object that will be serialized as JSON by json.dumps().
        """
        # Ensure that arbitrary objects -- such as Django model
        # instances or querysets -- can be serialized as JSON.
        return context


@method_decorator(decorators, name="dispatch")
class BaseView(JSONResponseMixin, TemplateView):
    template_name = ""
    extra_context = None

    def render_to_response(self, context):
        # Look for a 'format=json' GET argument
        if self.request.GET.get("format") == "json":
            return self.render_to_json_response(context)
        else:
            return super().render_to_response(context)

    def get_context_data(self, *args, **kwargs):
        context = super(BaseView, self).get_context_data(*args, **kwargs)
        if self.extra_context:
            context.update(self.extra_context)
        context.update(self.get_context())
        return context

    def get_context(self) -> dict:
        """
        adds custom context to response
        can be overridden in children classes
        """
        context = dict()
        return context


class HomePageView(BaseView):
    template_name = "home.html"


class HoursView(BaseView):
    template_name = "hours.html"


class PersonalInfoView(BaseView):
    template_name = "personal_info.html"

    def post(self, request):
        context = {}
        if request.POST.get("saveUserData"):
            self.save_user_data(request)
            context = {"submitted": True}
            return super(TemplateView, self).render_to_response(context)

    def save_user_data(self, request):
        request.user.first_name = request.POST.get("firstName", "")
        request.user.last_name = request.POST.get("lastName", "")
        request.user.first_name_p = request.POST.get("firstNameP", "")
        request.user.last_name_p = request.POST.get("lastNameP", "")
        request.user.national_ID = request.POST.get("nationalID", "")
        request.user.dob = request.POST.get("dob", "")
        request.user.email = request.POST.get("email", "")
        request.user.mobile1 = request.POST.get("mobile1", "")
        request.user.mobile2 = request.POST.get("mobile2", "")
        request.user.emergency_phone = request.POST.get("emergencyPhone", "")
        request.user.address = request.POST.get("address", "")
        request.user.laptop_info = request.POST.get("laptopInfo", "")
        request.user.bank_name = request.POST.get("bankName", "")
        request.user.card_number = request.POST.get("cardNumber", "")
        request.user.account_number = request.POST.get("accountNumber", "")
        request.user.SHEBA_number = request.POST.get("SHEBANumber", "")
        if request.FILES.get("personalImage"):
            personal_image = request.FILES["personalImage"]
            request.user.personal_image.save(personal_image.name, personal_image)
        if request.FILES.get("nationalIDFrontImage"):
            national_ID_front_image = request.FILES["nationalIDFrontImage"]
            request.user.national_ID_front_image.save(
                national_ID_front_image.name, national_ID_front_image
            )
        if request.FILES.get("nationalIDBackImage"):
            national_ID_back_image = request.FILES["nationalIDBackImage"]
            request.user.national_ID_back_image.save(
                national_ID_back_image.name, national_ID_back_image
            )
        if request.FILES.get("birthCertFirstPage"):
            birth_cert_first_page = request.FILES["birthCertFirstPage"]
            request.user.birth_cert_first_page.save(
                birth_cert_first_page.name, birth_cert_first_page
            )
        if request.FILES.get("birthCertChangesPage"):
            birth_cert_changes_page = request.FILES["birthCertChangesPage"]
            request.user.birth_cert_changes_page.save(
                birth_cert_changes_page.name, birth_cert_changes_page
            )
        if request.FILES.get("studentCard"):
            student_card = request.FILES["studentCard"]
            request.user.student_card.save(student_card.name, student_card)
        if request.FILES.get("militaryServiceCard"):
            military_service_card = request.FILES["militaryServiceCard"]
            request.user.military_service_card.save(
                military_service_card.name, military_service_card
            )
        request.user.save()


class DailyReport(BaseView):
    template_name = "daily_report.html"

    def post(self, request):
        context = {}
        if request.POST.get("saveUserData"):
            self.save_user_data(request)
            context = {"submitted": True}
            return super(TemplateView, self).render_to_response(context)


@method_decorator([daily_report_manager_required], name="dispatch")
class DailyReportManagement(BaseView):
    template_name = "daily_report_management.html"

    # def get_context_data(self, **kwargs):
    #     """
    #     Override this method to add context to the template.
    #     """
    #     context = super().get_context_data(**kwargs)
        
    #     if self.request.user.is_staff:
    #         user_role = 'admin'
    #     elif self.request.user.groups.filter(name='Manager').exists():
    #         user_role = 'manager'
    #     else:
    #         user_role = 'user'
        
    #     context['user_role'] = user_role
        
    #     return context    
        
    def post(self, request):
        context = {}
        if request.POST.get("saveUserData"):
            self.save_user_data(request)
            context = {"submitted": True}
            return super(TemplateView, self).render_to_response(context)


class HoursInfoView(BaseView):
    template_name = "hours_info.html"


@method_decorator([project_report_manager_required], name="dispatch")
class ReportsView(BaseView):
    template_name = "reports.html"


@method_decorator([financial_manager_required], name="dispatch")
class PaymentHandleView(BaseView):
    template_name = "payment.html"


class FoodFormView(BaseView):
    template_name = "food_form.html"


@method_decorator([food_manager_required], name="dispatch")
class FoodDataView(BaseView):
    template_name = "food_data.html"


@method_decorator([project_report_manager_required], name="dispatch")
class DetailedReportView(View):

    def get(self, request):

        year = request.GET.get("year")
        month = request.GET.get("month")
        sheets = Sheet.objects.filter(year=year, month=month)

        buffer = io.BytesIO()
        writer = pd.ExcelWriter(buffer, engine="xlsxwriter")
        for sheet in sheets:
            df = pd.DataFrame(sheet.data)
            df.to_excel(writer, sheet_name=sheet.user.get_full_name())
        writer.close()

        response = HttpResponse(
            buffer.getvalue(),
            content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
        response["Content-Disposition"] = (
            f"attachment; filename=detailed_report_{year}_{month}.xlsx"
        )
        return response


@method_decorator([project_report_manager_required], name="dispatch")
class MainReportView(View):

    def get(self, request):

        year = request.GET.get("year")
        month = request.GET.get("month")
        sheets = Sheet.objects.filter(year=year, month=month)
        sheetless_users = User.objects.select_related().exclude(
            sheets__year=year, sheets__month=month
        )

        hours, payments = MonthlyReportApiView.get_sheet_sums(sheets, sheetless_users)
        hours_df = pd.DataFrame(hours).transpose()
        hours_df = hours_df.reindex(np.roll(hours_df.index, 1))
        payments_df = pd.DataFrame(payments).transpose()

        buffer = io.BytesIO()
        writer = pd.ExcelWriter(buffer, engine="xlsxwriter")
        hours_df.to_excel(writer, sheet_name="hours")
        payments_df.to_excel(writer, sheet_name="payments")
        writer.close()

        response = HttpResponse(
            buffer.getvalue(),
            content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
        response["Content-Disposition"] = (
            f"attachment; filename=main_report_{year}_{month}.xlsx"
        )
        return response


@method_decorator([project_report_manager_required], name="dispatch")
class UsersMonthlyReportView(View):

    def get(self, request):

        year = request.GET.get("year")
        users = User.objects.all()
        data = dict()
        for u in users:
            sheets = Sheet.objects.filter(year=year, user=u).values("month", "total")
            data[u.get_full_name()] = {
                sheet["month"]: round(sheet["total"] / 60, 2) for sheet in sheets
            }

        df = pd.DataFrame(data)
        df = df.transpose()
        df = df[sorted(df)]
        df["total"] = df.sum(axis=1)

        buffer = io.BytesIO()
        writer = pd.ExcelWriter(buffer, engine="xlsxwriter")
        df.to_excel(writer, sheet_name="hours")
        writer.close()

        response = HttpResponse(
            buffer.getvalue(),

hours/sheets/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ request.resolver_match.url_name }}</title>
    <link rel="icon" href="{% static 'sheets/picture/favicon.ico' %}">
    {% block main_css %}
    <link rel="stylesheet" href="{% static 'sheets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'sheets/css/jsuites.css' %}">
    <link rel="stylesheet" href="{% static 'sheets/css/font-awesome-all.min.css' %}">
    {% endblock main_css %}

    {% block extra_css %}
    {% endblock extra_css %}

    <style>
        @font-face {
            font-family: 'lato';
            src: local('Lato'),
            url('{% static "sheets/fonts/Lato-Italic.ttf" %}');
        }

        body {
            font-family: 'Lato', sans-serif;
        }

        .logout {
            color: rgba(255, 0, 0, 0.7);
        }

        .logout:hover {
            color: red;
        }

        /* Chrome, Safari, Edge, Opera */
        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }
        /* Firefox */
        input[type=number] {
            -moz-appearance: textfield;
            appearance: auto;
        } 
    </style>

    <script src="{% static 'sheets/js/JQuery-3.6.0.min.js' %}"></script>
    <script src="{% static 'sheets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'sheets/js/jdate.min.js' %}"></script>
    <script src="{% static 'sheets/js/jsuites.js' %}"></script>
    <script src="{% static 'sheets/js/utils.js' %}"></script>
</head>

<body style="letter-spacing: 0.5px;">

    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"> <span style="color: blue">W<span style="color: yellow">i</span>se</span>
                Hours</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'sheets:home_page' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        {% url 'sheets:hours' as temp_url %}
                        <a class="nav-link {% if request.path == temp_url %}active{% endif %}"
                            href="{% url 'sheets:hours' %}">Hours</a>
                    </li>
                    <!-- <li class="nav-item">
                        {% url 'sheets:food_form' as temp_url %}
                        <a class="nav-link {% if request.path == temp_url %}active{% endif %}"
                            href="{% url 'sheets:food_form' %}">Foods</a>
                    </li>
                    <li class="nav-item">
                        {% url 'sheets:daily_report' as temp_url %}
                        <a class="nav-link {% if request.path == temp_url %}active{% endif %}"
                            href="{% url 'sheets:daily_report' %}">Daily Report</a>
                    </li> -->
                    <li class="nav-item">
                        {% url 'sheets:hours_info' as temp_url %}
                        <a class="nav-link {% if request.path == temp_url %}active{% endif %}"
                            href="{% url 'sheets:hours_info' %}">Hours Info</a>
                    </li>
                    <li class="nav-item">
                        {% url 'sheets:personal_info' as temp_url %}
                        <a class="nav-link {% if request.path == temp_url %}active{% endif %}"
                            href="{% url 'sheets:personal_info' %}">Personal Info</a>
                    </li>
                    {% if request.user.is_ProjectReportManager %}
                    <li class="nav-item">
                        {% url 'sheets:reports' as temp_url %}
                        <a class="nav-link {% if request.path == temp_url %}active{% endif %}"
                        href="{% url 'sheets:reports' %}">Reports</a>
                    </li>
                    {% endif %}
                    {% if request.user.is_FinancialManager %}
                    <li class="nav-item">
                        {% url 'sheets:payment' as temp_url %}
                        <a class="nav-link {% if request.path == temp_url %}active{% endif %}"
                        href="{% url 'sheets:payment' %}"> Payments</a>
                    </li>
                    {% endif %}
                    {% if request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    {% endif %}

                    {% if request.user.is_FoodManager %}
                    <li class="nav-item">
                        {% url 'sheets:food_data' as temp_url %}
                        <a class="nav-link {% if request.path == temp_url %}active{% endif %}"
                            href="{% url 'sheets:food_data' %}">Food Data</a>
                    </li>
                    {% endif %}

                    {% if request.user.is_MainReportManager or request.user.is_SubReportManager %}
                    <li class="nav-item">
                        {% url 'sheets:daily_report_management' as temp_url %}
                        <a class="nav-link {% if request.path == temp_url %}active{% endif %}"
                            href="{% url 'sheets:daily_report_management' %}">Daily Report Management</a>
                    </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link logout" href="{% url 'sheets:logout' %}">Logout</a>
                    </li>
                </ul>
                <span class="navbar-text" style="color: cornsilk;">
                    <span class="mx-3">{{ request.user.username }}</span>
                    <span id="nav-date"></span>
                </span>
            </div>
        </div>
    </nav>
    {% endblock navbar %}

    <script>
        window.START_YEAR = 2020;
        window.CSRF_TOKEN = "{{ csrf_token }}";

        function getToday() {
            const today = new Date();
            const y = today.getFullYear();
            const m = today.getMonth();
            const d = today.getDate();
            return [y, m, d]
        }

        function writeDate() {
            const [y, m, d] = getToday();
            const weekday = new Date().toLocaleString('en-us', { weekday: 'short' });
            $("#nav-date").text(`${weekday}.\u00A0\u00A0|\u00A0\u00A0${y}/${m+1}/${d}`);
        }
        writeDate();
    </script>

    {% block body %}
    {% endblock body %}


</body>

</html>

hours/sheets/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<style>
    body {
        /* background-color: #5b6467;
        background-image: linear-gradient(315deg, #5b6467 0%, #8b939a 59%); */
        height: 100vh;
        background-color: #c2b6b6;
        background-image: linear-gradient(315deg, #c2b6b6 0%, #576574 74%);
    }

    .card-container {
        display: flex;
        justify-content: center;
    }

    .card-link {
        color: black;
        text-decoration: none;
    }

    .card-link:hover {
        color: black;
        transition: all 0.01s ease-in;
    }

    .card {
        background-color: #e0e4ee;
    }

    .card:hover {
        background-color: #bcc5db;
        transition: all 0.1s ease-in;
    }
</style>
{% endblock extra_css %}

{% block navbar %}
{% endblock navbar %}

{% block body %}
<div class="container p-5">
    <div class="d-flex flex-column justify-content-center align-items-center">
        <h1 class="my-5 py-5" style="font-weight: bold;
                       font-size: 5em;
                       text-align: center">
            <span style="color: blue">W<span style="color: yellow">i</span>se</span> Hours
        </h1>

        <div class="row">

            <div class="col-lg-4 col-md-6 mb-2 card-container">
                <a href="{% url 'sheets:hours' %}" class="card-link">
                    <div class="card mx-3" style="width: 19rem;">
                        <div class="card-body">
                            <h5 class="card-title">
                                My Hours
                            </h5>
                            <p class="card-text">
                                Edit your hours
                            </p>
                        </div>
                    </div>
                </a>
            </div>


            <div class="col-md-3 mb-2 mx-auto card-container">
                <a href="{% url 'sheets:hours_info' %}" class="card-link">
                    <div class="card mx-3" style="width: 19rem;">
                        <div class="card-body">
                            <h5 class="card-title">
                                Info
                            </h5>
                            <p class="card-text">
                                Information about hours in <span style="color: blue">Wise grid</span>
                            </p>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-md-3 mb-2 mx-auto card-container">
                <a href="{% url 'sheets:personal_info' %}" class="card-link">
                    <div class="card mx-3" style="width: 19rem;">
                        <div class="card-body">
                            <h5 class="card-title">
                                Personal Info
                            </h5>
                            <p class="card-text">
                                Your personal information
                            </p>
                        </div>
                    </div>
                </a>
            </div>
        </div>

        <!-- <div class="mt-5">
            <a class="btn btn-danger" href="{% url 'sheets:logout' %}" style="width: 250px;">Logout</a>
        </div> -->
        {% if request.user.is_staff or request.user.is_FoodManager %}
        <div class="mt-5 d-flex flex-wrap">
            {% if request.user.is_staff %}
            <a class="btn btn-primary mx-1" href="{% url 'admin:index' %}" style="width: 200px">Admin Panel</a>
            {% endif %}
            {% if request.user.is_ProjectReportManager %}
            <a class="btn btn-success mx-1" href="{% url 'sheets:reports' %}" style="width: 200px">Reports</a>
            {% endif %}
            {% if request.user.is_FinancialManager %}
            <a class="btn btn-danger mx-1" href="{% url 'sheets:payment' %}" style="width: 200px"> Payments</a>
            {% endif %}

            <!-- {% if request.user.is_FoodManager %}
            <a class="btn btn-info mx-1" href="{% url 'sheets:food_data' %}" style="width: 200px">Food Data</a>
            {% endif %}
            {% if request.user.is_MainReportManager or request.user.is_SubReportManager %}
            <a class="btn btn-warning mx-1" href="{% url 'sheets:daily_report_management' %}" style="width: 250px">Daily
                report management</a>
            {% endif %} -->
        </div>
        {% endif %}

    </div>
</div>
{% endblock body %}

hours/sheets/templates/login.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}

    <head>

        <meta charset="UTF-8">

        <meta name="viewport"
              content="width=device-width, initial-scale=1.0, user-scalable=no">

        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{{ request.resolver_match.url_name }}</title>

        <link rel="icon" href="{% static 'sheets/picture/favicon.ico' %}">

        <link rel="stylesheet" href="{% static 'sheets/css/bootstrap.min.css' %}">

        <link rel="stylesheet" href="{% static 'sheets/css/loginpage.css' %}">

        <style>
		@font-face {
			font-family: 'lato';
			src: local('Lato'),
				url('{% static "sheets/fonts/Lato-Italic.ttf" %}');
		}
		body{
			font-family: 'Lato', sans-serif;
		}
		.esfa-icon{
			width: 75px;
			margin: 22px 5px;
		}
		.msg{
			margin-left: 25px;
			margin-right: 25px;
			padding: 5px;
			border-radius: 8px;
		}
		.error-msg{
			background-color: rgba(255, 0, 0, 0.1);
			color: red;
			border: 1px solid red;
		}
		.success-msg{
			background-color: rgba(0, 255, 0, 0.1);
			color: green;
			border: 1px solid green;
		}
		button{
			margin: 10px 15px 20px 15px;
		}
	
        </style>
    </head>

    <body>

        <div class="wrapper fadeInDown">

            <div id="formContent">

                <!-- Header -->

                <div class="fadeIn first my-2">
                    <strong style="color: black; font-size: 2em;"><span style="color: blue;">W<span style="color: yellow;">i</span>se Hours</span></strong>

                </div>

                <!-- Login Form -->

                <form action="{% url 'sheets:login' %}" method="post">
                    {% csrf_token %}

                    <input type="hidden" name="login_submit" value="true">

                    <input type="text"
                           id="username"
                           class="fadeIn third"
                           name="username"
                           placeholder="Username *"
                           required
                           value="{{ username }}">

                    <input type="password"
                           id="password"
                           class="fadeIn sixth"
                           name="password"
                           placeholder="Password *"
                           required>

                    <hr class="fadeIn sixth">

                    <div class="fadeIn eighth">

                        <button class="btn btn-primary" id="signup" style="width: 150px;">
                            Login
                        </button>

                    </div>

                </form>


                {% if not_authenticated %}

                    <p class="fadeIn eighth msg error-msg" style="color: red;">
                        Wrong username or password

                    </p>

                {% endif %}

                <!-- Change Passowrd -->

                <div id="formFooter" style="display: flex; justify-content: space-around">
                    <a class="underlineHover" href="{% url 'sheets:signup' %}">Signup</a>
                    <a class="underlineHover" href="{% url 'sheets:change_password' %}">Change Password</a>

                </div>


            </div>

        </div>

    </body>

</html>